config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users, only: [:show] do
    resources :recipes
  end
  authenticated :user do
    root 'recipes#index'
  end
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  accepts_nested_attributes_for :recipe_ingredients,
    reject_if: :all_blank,
    allow_destroy: true
  # has_many :steps
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
  acts_as_list, scope: :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @recipe.recipe_ingredients.build
    @ingredients = Ingredient.all.pluck(:name, :id)
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to [current_user, @recipe], notice: 'Recipe added'
    else
      flash[:error] = 'Fail'
      render :new
    end
  end

  def edit
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :cuisine, :category, :time, :serving_size,
      recipe_ingredients_attributes: [:id, :ingredient_id, :quantity])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/home/index.html.erb
<div class="inner cover">
  <h1 class="cover-heading">Best of all recipe sites!</h1>
  <p class="lead"><%= Faker::Lorem.paragraph %></p>
  <p class="lead">
    <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-lg btn-secondary" %>
  </p>
</div>

<div class="mastfoot">
  <div class="inner">
    <p>Copyright <%= Date.today.year %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipez</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipez</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="awesome recipe site">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Recipeeze</h3>
              <nav class="nav nav-masthead">
                <a class="nav-link active" href="#">Home</a>
                <a class="nav-link" href="#">Features</a>
                <a class="nav-link" href="#">Contact</a>
              </nav>
            </div>
          </div>

          <%= yield %>

        </div>
      </div>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= bootstrap_form_for [current_user, @recipe] do |f| %>
  <%= f.text_field :name %>
  <%= f.select :cuisine, %w(French Chinese Mexican Italian Swedish Indian Japanese Thai) %>
  <%= f.select :category, %w(Appetizer Breakfast Lunch Dinner) %>
  <%= f.select :time, (15..90).step(15).to_a %>
  <%= f.select :serving_size, (1..8).to_a %>

  <h3>Ingredients</h3>
  <div id="ingredients">
    <%= f.fields_for :recipe_ingredients do |ff| %>
      <%= render 'recipe_ingredient_fields', f: ff %>
    <div class="links">
      <%= link_to_add_association 'Add ingredient', f, :recipe_ingredients %>
    </div>
    <% end %>
  </div>
  <%= f.submit %>
<% end %>

app/views/recipes/_recipe_ingredient_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.select :ingredient_id, @ingredients %>
  </div>
  <div class="field">
    <%= f.number_field :quantity %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Recipes#edit</h1>
<p>Find me in app/views/recipes/edit.html.erb</p>

app/views/recipes/index.html.erb
<%= link_to 'Add recipe', new_user_recipe_path(current_user), class: 'btn btn-secondary' %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>
<%= render 'form' %>

app/views/recipes/show.html.erb
<h1>Recipe: <%= @recipe.name %></h1>

<h3>Ingredients</h3>
<% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
  <p><b><%= recipe_ingredient.quantity %></b> <%= recipe_ingredient.ingredient.name %></p>
<% end %>